[package]
name = "hmac_breaker"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version = "0.11.4", features = ["blocking"] }
clap = "3.0.0-beta.4"
hex = "0.4.3"
